Completed multiple cursors
IEEE-NITK/codeshare pull request #3
Opened 2019-12-12 19:11 UTC by harsh2338

2019-12-13 19:08 UTC, rohit-mp approved these changes

2019-12-13 20:57 UTC, rohit-mp requested changes

2019-12-13 20:57 UTC, rohit-mp commented on assets/js/app.js
> +        markers[payload.user_name] = cm.setBookmark(payload.cursorPos, { widget: cursor });
add option to handle mouse events on the bookmark:
```markers[payload.user_name] = cm.setBookmark(payload.cursorPos, { widget: cursor , handleMouseEvents: true});```

2019-12-14 08:10 UTC, rohit-mp approved these changes

2019-12-14 09:22 UTC, shanthanu9 approved these changes

2019-12-14 09:22 UTC, merged